# MAKEFILE FOR AZTEC C

CCC = cc.com
ASM = as.com
LNK = ln.com

all:	clib clibtest

clib:
	$(CCC) memcpy.c
	$(CCC) strchr.c
	$(CCC) strstr.c
	$(ASM) memcpy.asm
	$(ASM) strchr.asm
	$(ASM) strstr.asm

clibtest:
	$(CCC) clibtest.c
	$(ASM) clibtest.asm
	$(LNK) -o clibtest.com clibtest.o memcpy.o strchr.o strstr.o c.lib
