# MAKEFILE FOR AZTEC C

CCC = cc.com
ASM = as.com
LNK = ln.com

all:	ue ueshl

ue:
	$(CCC) ue.c
	$(ASM) ue.asm
	$(LNK) -o ue.com ue.o c.lib

ueshl:
	$(CCC) -dSHL ue.c
	$(ASM) ue.asm
	$(LNK) -o ue.com ue.o shl.o strchr.o strstr.o c.lib
